# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['src/app/main.py'],
    pathex=['src'],
    binaries=[],
    datas=[
        ('src/images', 'images'),
        ('src/i18n/locales', 'i18n/locales')
    ],
    hiddenimports=[
        'ui.main_window',
        'ui.pages.dashboard_page',
        'ui.pages.starter_page',
        'ui.pages.admin_page',
        'ui.pages.coming_soon_page',
        'ui.tabs.startup_status_tab',
        'ui.tabs.favourite_tab',
        'ui.tabs.all_apps_tab',
        'ui.tabs.settings_tab',
        'ui.tabs.languages_tab',
        'ui.tabs.trigger_tab',
        'ui.tabs.rules_tab',
        'ui.theme',
        'i18n.translator',
        'storage.config_store',
        'services.system_metrics_service',
        'services.startup_monitor_service',
        'services.discovery_service',
        'services.launcher_service',
        'services.startup_service',
        'services.url_service',
        'models.config_models',
        'utils.paths',
        'PySide6.QtCore',
        'PySide6.QtGui',
        'PySide6.QtWidgets',
        'qtawesome',
        'psutil',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='StarterAppLauncher',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='src/images/avatar.png',
    uac_admin=False,
    uac_uiaccess=False,
    manifest='app.manifest',
)
